Analytics
alushpanov/news_project pull request #14
Opened 2021-03-31 10:01 UTC by alushpanov

2021-04-03 11:11 UTC, makushenk commented
@alushpanov конфликты

2021-04-04 09:05 UTC, makushenk requested changes

2021-04-04 09:05 UTC, makushenk commented on my_auth/managers.py
> +        most_commenting = qs_comments_counted.aggregate(Max('comments_count'))
вместо аггрегации ты можешь просто сделать order_by по comments_count и вернуть первого. Будет на один запрос меньше в базу

2021-04-04 09:05 UTC, makushenk commented on news/managers.py
> +        return self.get_queryset().filter(q).order_by('-created_at')
почитай про distinct(). Запрос на поиск работает не корректно

2021-04-06 08:50 UTC, alushpanov commented on news/managers.py
> +        return self.get_queryset().filter(q).order_by('-created_at')
слушай, я понимаю, что такое distinct, и видимо применять его нужно после фильтрации по Q-объектам. Но как ты понял, что запрос работает не корректно?

2021-04-14 07:57 UTC, merged