primitive authentication added
alushpanov/news_project pull request #2
Opened 2021-03-09 14:49 UTC by alushpanov

2021-03-11 07:38 UTC, alushpanov commented
authentication finished

2021-03-14 20:09 UTC, makushenk requested changes

2021-03-14 20:09 UTC, makushenk commented on .gitignore
> +my_auth/migrations/__pycache__/
Попробуй заменить все это на одну строчку ***.pyc**

2021-03-14 20:09 UTC, makushenk commented on my_auth/forms.py
> +from my_auth.models import MyUser
импорты из библиотек и собственных модулей одной пустой строкой разделяют

2021-03-14 20:09 UTC, makushenk commented on my_auth/models.py
> +from django.contrib.auth.base_user import BaseUserManager
Порекомендовал бы сортировать импорты по алфавиту

2021-03-14 20:09 UTC, makushenk commented on my_auth/models.py
> +class CustomUserManager(BaseUserManager):
Лучше хранить менеджеры отдельно от моделей. Создай файл **managers.py** и перенеси класс менеджера туда

2021-03-14 20:09 UTC, makushenk commented on my_auth/models.py
> +class MyUser(AbstractUser):
Именований **MyUser** или **my_auth** лучше избегать в реальных проектах. Исправлять это не нужно, так как может возникнуть боль в некоторых местах. Просто учитывай на будущее :)

2021-03-14 20:09 UTC, makushenk commented on news_project/settings.py
> +    'django.contrib.sites',
Если библиотека **allauth** не требует, что бы **django.contrib.sites** находилась в списке после нее (самой allauth), то укажи **django.contrib.sites** рядом с другими приложениями джанги. затем укажи приложения сторонних библиотек, затем свои приложения

2021-03-14 20:09 UTC, makushenk commented on news_project/settings.py
> +        'DIRS': ['news_project/templates'],
Указывай путь относительно переменной BASE_DIR

2021-03-16 09:24 UTC, makushenk approved these changes

2021-03-16 09:24 UTC, merged