Whole drf
alushpanov/news_project pull request #23
Opened 2021-04-21 20:39 UTC by alushpanov

2021-04-22 09:01 UTC, makushenk requested changes

2021-04-22 09:01 UTC, makushenk commented on news/api/serializers.py
> +            old_image_name = instance.image.name.split('/')[-1]
смотри, я могу загружать абсолютно разные картинки с одинаковым именем? Что тогда произойдет?
И вообще не совсем понял зачем тут нужна проверка. Если тебе не приходит изображение, то ты ничего не делаешь, а если приходит - то всегда меняешь

2021-04-22 09:01 UTC, makushenk commented on news/api/serializers.py
> +        super().update(article, validated_data)
лучше вызывать метод create, а не update.

Ты можешь дописать в validated_date нужные поля и вызвать create

2021-04-22 09:01 UTC, makushenk commented on news/api/serializers.py
> +        comment = Comment(
То же самое, что и в ArticleSerializer

2021-04-22 09:01 UTC, makushenk commented on news/api/serializers.py
> +        validated_data['num_likes'] = instance.num_likes
у тебя же num_likes - аннотированное поле, зачем ты его обновляешь?

2021-04-22 09:01 UTC, makushenk commented on news/api/serializers.py
> +        super().update(category, validated_data)
то же самое, что в ArticleSerializer

2021-04-22 09:01 UTC, makushenk commented on news/api/views.py
> +            instance_id = request.query_params['article_id']
а что будет, если одновременно в теле запроса придет и article_id и comment_id?

2021-04-22 09:01 UTC, makushenk commented on news/managers.py
> +        return super().get_queryset().annotate(num_likes=Count('likes')).filter(archived=False)
У тебя теперь всегда аннотируется кверисет статей, а нужно, чтобы аннотировался только тогда, когда тебе нужна

2021-04-22 09:01 UTC, makushenk commented on news/managers.py
> +        return super().get_queryset().annotate(num_likes=Count('likes'))
то же самое, что и со статьями

2021-04-22 09:01 UTC, makushenk commented on notifications/api/views.py
> +class IsReceiver(permissions.BasePermission):
тут ты не не вынес пермишены, в другом джанго приложении вынес)

сделай унифицировано (лучше вынести везде)

2021-04-22 09:01 UTC, makushenk commented on notifications/models.py
> +    def create_from_instance(cls, instance, signal_sender):
1. Вынеси эту логику в отдельное место
2. Проверяй явно каждый случай. У тебя сейчас их всего два, и ты используешь блок else. Как только появится третий случай - код начнет приносить проблемы и его нужно менять будет

2021-04-22 09:01 UTC, makushenk commented on news/signals.py
> +replace_image.connect(remove_image)
не пойму предназначение этих строк)

2021-04-22 09:01 UTC, makushenk commented on news/api/serializers.py
> +class Base64ImageField(serializers.ImageField):
лучше сделать отдельный модуль fields (в папке api) и там хранить

2021-04-22 09:01 UTC, makushenk commented on news/api/serializers.py
> +from news.signals import replace_image
зачем импортить сигнал тут?

2021-04-22 09:01 UTC, makushenk commented on news/api/views.py
> +        # if request.user.has_perm(IsUserWhoLiked, like_obj):  # always False
он false, потому что это пермишены джанги по идее, и они работают иначе, нежели пермишены дрф)

2021-04-22 09:01 UTC, makushenk commented on news/api/views.py
> +            return Response(status=status.HTTP_200_OK)
при успешном удалении возвращается 204

2021-04-22 09:01 UTC, makushenk commented on news/api/views.py
> +        return Response(serializer.data)
при успешном создании код 201

2021-04-22 09:01 UTC, makushenk commented on news/api/views.py
> +        'most_liked_article_id': Article.objects.get_most_liked_article().id,
если ты сделаешь все методы аналитики доступными для кверисета, тебе не придется делать миллион разных кверисетов (и запросов в базу соответственно)

2021-04-25 14:21 UTC, alushpanov commented on news/signals.py
> +replace_image.connect(remove_image)
Функция remove_image связана с post_delete и моим replace_image. replace_image послыается из одного места: метода update в ArticleSerializer в случае, если загружена новая картинка

2021-04-25 14:21 UTC, alushpanov commented on news/api/serializers.py
> +from news.signals import replace_image
ответил выше

2021-04-26 10:26 UTC, makushenk commented on news/api/serializers.py
> +        if 'image' in self.context['request'].data:
Зачем вручную вызывать сигнал? его смысл в том, чтобы этого не делать)

2021-04-26 10:26 UTC, makushenk commented on news/api/serializers.py
> +        validated_data['article_id'] = self.context['request'].query_params['article_id']
id статьи лучше передавать в теле запроса. Не увидел в прошлый раз

2021-04-26 10:26 UTC, makushenk commented on news/api/serializers.py
> +        if object_type is not Article and object_type is not Comment:
используй конструкцию **not in [Comment, Article]**

2021-04-26 10:26 UTC, makushenk commented on news/api/serializers.py
> +from news.signals import replace_image
@alushpanov не вижу))

2021-04-26 10:29 UTC, makushenk commented on news/signals.py
> +replace_image.connect(remove_image)
Вопрос был в том, зачем создавать пустой сигнал и коннектить к нему функцию? Есть декораторы, которыми можно обернуть функцию

https://docs.djangoproject.com/en/3.2/topics/signals/#connecting-to-signals-sent-by-specific-senders

2021-04-26 11:00 UTC, alushpanov commented on news/api/serializers.py
> +        if 'image' in self.context['request'].data:
я зарегистрировал свой пустой сигнал, чтобы он срабатывал только при одном условии.
Если его убрать, то мне нужно навешивать pre_save. Но тогда он будет срабатывать при каждом сохранении модели, даже когда новое изображение поступать не будет.
Если принять этот вариант, то я не понимаю, как мне в remove_image проверять, есть ли новое изображение? Или мы подразумеваем, что изображение удаляется всегда?

2021-04-26 11:04 UTC, makushenk commented on news/api/serializers.py
> +        if 'image' in self.context['request'].data:
У тебя при использовании сигнала pre_save, есть такой аргумент, как update_fields
если в там будет содержаться image, значит изображение изменилось

2021-04-26 11:04 UTC, makushenk commented on news/api/serializers.py
> +        if 'image' in self.context['request'].data:
https://docs.djangoproject.com/en/3.2/ref/signals/#pre-save

2021-04-26 11:05 UTC, makushenk commented on news/api/serializers.py
> +        if 'image' in self.context['request'].data:
Изображение удаляется:
1. Всегда при удалении статьи
2. При изменении удаляется только старое изображение, если было загружено новое

2021-04-26 14:33 UTC, makushenk requested changes

2021-04-26 14:33 UTC, makushenk commented on news/api/serializers.py
> +        validated_data['article_id'] = self.context['request'].data['article_id']
а почему ты не добавил это в поле сериалайзера?)

2021-04-26 14:46 UTC, makushenk approved these changes

2021-04-27 15:21 UTC, merged