News dashboard
alushpanov/news_project pull request #3
Opened 2021-03-11 10:58 UTC by alushpanov

2021-03-14 20:23 UTC, makushenk requested changes
файл базы и те файлы, которые пользователь загружает не должны находится в репозитории

2021-03-14 20:23 UTC, makushenk commented on news/admin.py
> +class MyArticleAdminForm(forms.ModelForm):
Вот тут уже убирай **My** из имени)

2021-03-14 20:23 UTC, makushenk commented on news/admin.py
> +admin.site.register(Article, ArticleAdmin)
Юзера ты регистировал через дерекоратор **@register** (https://github.com/alushpanov/news_project/pull/2/files#diff-9a6089421c8b0a19280698abd2a2e94c4695831a06840d187962b5320a69f57dR8). Выбери один стиль и придерживайся его

2021-03-14 20:23 UTC, makushenk commented on news/migrations/image_and_cat_not_required.py
> +class Migration(migrations.Migration):
ты можешь свернуть все миграции в один файл, так как они были сделаны в рамках одной фичи. 
Откатити миграции приложения **news** до нуля, затем удали все файлы миграций и сделай makemigrations.

2021-03-14 20:23 UTC, makushenk commented on news/models.py
> +from news_project import settings
вместо этого используй **from django.conf import settings**

2021-03-14 20:23 UTC, makushenk commented on news/models.py
> +    # author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
удали строчку, если она не нужна

2021-03-14 20:23 UTC, makushenk commented on news/urls.py
> +    # path('<int:question_id>/vote/', views.vote, name='vote'),
удали, если не нужно

2021-03-14 20:23 UTC, makushenk commented on news/models.py
> +    created_on = models.DateField()  # auto_now_add=True
обычно используют постфикс **_at**

2021-03-14 20:23 UTC, makushenk commented on news/models.py
> +    created_on = models.DateField()  # auto_now_add=True
Вместо DateField используй DateTimeField

2021-03-14 20:23 UTC, makushenk commented on news/models.py
> +    article_text = models.TextField()
слово **article** лишнее. И так понятно чей текст

2021-03-14 20:23 UTC, makushenk commented on news_project/settings.py
> +import os
сначала import, затем from

2021-03-14 20:23 UTC, makushenk commented on news_project/settings.py
> +        'DIRS': ['templates'],
Ты же создал переменную TEMPLATE_DIR

2021-03-14 20:23 UTC, makushenk commented on news_project/urls.py
> +from django.conf.urls.static import static
отсортируй

2021-03-14 20:23 UTC, makushenk commented on news_project/urls.py
> +from news_project import settings
from django.conf import settings

2021-03-16 09:25 UTC, makushenk commented
@alushpanov пофиксь конфликты плз)

2021-03-17 07:53 UTC, alushpanov commented
fixed

2021-03-17 09:10 UTC, makushenk requested changes

2021-03-17 09:10 UTC, makushenk commented on news/models.py
> +    author = models.ForeignKey(MyUser, on_delete=models.CASCADE)
модель юзера указывай не напрямую, а через настройки: settings.AUTH_USER_MODEL

2021-03-17 09:10 UTC, makushenk commented on news/views.py
> +def index_view(request):
Сделай классовую вьюху

2021-03-17 09:10 UTC, makushenk commented on news/views.py
> +    if request.user.is_authenticated:
В джанго есть специальный декоратор login_required для этих целей. Не нужно проверять вручную

2021-03-17 09:10 UTC, makushenk commented on news/views.py
> +    if request.user.is_authenticated:
https://docs.djangoproject.com/en/3.1/topics/auth/default/#the-login-required-decorator

2021-03-18 10:43 UTC, makushenk requested changes

2021-03-18 10:43 UTC, makushenk commented on news/urls.py
> +    path('', login_required(views.IndexView.as_view()), name='index'),
так можно делать, но у такого подхода есть минусы
сделай вот так
https://docs.djangoproject.com/en/3.1/topics/class-based-views/intro/#decorating-the-class

2021-03-18 12:33 UTC, merged