Create news
alushpanov/news_project pull request #7
Opened 2021-03-16 10:10 UTC by alushpanov

2021-03-17 09:47 UTC, makushenk requested changes

2021-03-17 09:47 UTC, makushenk commented on news/admin.py
> +class ArticleAdminForm(forms.ModelForm):
перенеси формы в отдельный модуль

2021-03-17 09:47 UTC, makushenk commented on news/admin.py
> +    def clean_categories(self):
Зачем дублировать логику в форме, если она уже есть в модели?

2021-03-17 09:47 UTC, makushenk commented on news/models.py
> +    author = models.ForeignKey(User, on_delete=models.CASCADE)
Указывай юзера через настройки

2021-03-17 09:47 UTC, makushenk commented on news/migrations/image_added.py
> +class Migration(migrations.Migration):
объедини миграции в одну

2021-03-17 09:47 UTC, makushenk commented on news/forms.py
> +    def clean_categories(self):
Аналогично. Дублируешь валидацию

2021-03-18 12:34 UTC, makushenk commented
@alushpanov конфликты)

2021-03-18 13:29 UTC, alushpanov commented
@makushenk fixed

2021-03-18 13:40 UTC, makushenk requested changes

2021-03-18 13:40 UTC, makushenk commented on news/models.py
> +    image = models.ImageField(upload_to='', null=True, blank=True)
укажи конкретный путь. Что то вроде **'news/articles/images/[user_id]/filename.jpg'**

2021-03-18 13:42 UTC, makushenk commented
@alushpanov и конфликты пофиксь)

2021-03-19 07:58 UTC, makushenk approved these changes

2021-03-19 07:58 UTC, merged