User news
alushpanov/news_project pull request #9
Opened 2021-03-24 06:58 UTC by alushpanov

2021-03-24 08:37 UTC, makushenk commented
@alushpanov пофиксь конфликты)

2021-03-24 12:02 UTC, alushpanov commented
fixed

2021-03-24 14:48 UTC, makushenk requested changes

2021-03-24 14:48 UTC, makushenk commented on my_auth/forms/register.py
> +class MyRegisterForm(MyLoginForm):
Уже писал по поводу **My** в именованиях: 
https://github.com/alushpanov/news_project/pull/2#discussion_r593952577

Убери везде, кроме модели, так как ее исправлять будет геморно

2021-03-24 14:48 UTC, makushenk commented on news/models.py
> +    all_articles = models.Manager()
лучше используй **all_objects** тогда

2021-03-24 14:48 UTC, makushenk commented on news/views.py
> +def archive(request, pk):
укажи в названии что именно архивируется

2021-03-24 14:48 UTC, makushenk commented on news/views.py
> +class ArticleUpdate(generic.UpdateView):
Добвляй слово **View** в именование

2021-03-24 14:48 UTC, makushenk commented on news/urls.py
> +    path('mynews/<int:pk>/archive/', views.archive, name='archive'),
в name указывай **archive_news**, то же самое касается **edit**

2021-03-24 14:48 UTC, makushenk commented on news/views.py
> +class MyNewsView(generic.ListView):
если наследуешься от ListView, то имя вьюхи будет **NewsListView**

2021-03-24 14:48 UTC, makushenk commented on news/views.py
> +class MyNewsView(generic.ListView):
Еще не понятно, почему для Article где-то ты используешь это же слово, а где-то слово News. Сделай унифицировано

2021-03-25 08:37 UTC, alushpanov commented on news/views.py
> +class MyNewsView(generic.ListView):
не лучше ли сделать UserArticleListView? Ведь это статьи определённого пользователя, а не вообще все, для которых используется IndexView. Кстати, 2 вопроса по IndexView:
1) IndexView или IndexListView?
2) так всегда следует называть вьюху и темплейт для страницы индекса? Хочется написать ArticleListView.

2021-03-25 08:43 UTC, alushpanov commented on news/views.py
> +class MyNewsView(generic.ListView):
и сразу туда же: у меня ArticleForm наследуется от ModelForm, а LoginForm - от Form. Следует ли переименовать ArticleForm в ArticleModelForm?

2021-03-25 08:44 UTC, makushenk commented on news/views.py
> +class MyNewsView(generic.ListView):
0. Нет, не лучше. Мы же решили, что для новостей пользователя не будет отдельной вьюхи, а будет фильтр
1-2. У наименования index есть как преимущества, так и недостатки перед ArticleListView. В принципе, можешь переименовать)

2021-03-25 08:48 UTC, makushenk commented on news/views.py
> +class MyNewsView(generic.ListView):
> и сразу туда же: у меня ArticleForm наследуется от ModelForm, а LoginForm - от Form. Следует ли переименовать ArticleForm в ArticleModelForm?

хм, интересный вопрос. Если бы у тебя было две формы для Article, и одна бы из них наследовалась от Form, а другая от ModelForm, тогда может быть и был смысл. А так, мне кажется, что не стоит переименовывать.

2021-03-25 14:29 UTC, makushenk requested changes

2021-03-25 14:29 UTC, makushenk commented on my_auth/admin.py
> +class CustomUserAdmin(DjangoUserAdmin):
а почему ты не хочешь назвать. **UserAdmin** ?

2021-03-25 14:29 UTC, makushenk commented on my_auth/views.py
> +                user = MyUser.objects.create_user(
можно сделать MyUser.objects.create_user(**form.cleadned_data)

2021-03-25 14:36 UTC, alushpanov commented on my_auth/admin.py
> +class CustomUserAdmin(DjangoUserAdmin):
Я подумал, что это может сбить с толку. Просто так сразу понятно, что это не встроенный

2021-03-25 14:38 UTC, makushenk commented on my_auth/admin.py
> +class CustomUserAdmin(DjangoUserAdmin):
Окей)

2021-03-25 14:39 UTC, alushpanov commented on my_auth/admin.py
> +class CustomUserAdmin(DjangoUserAdmin):
не, тебе виднее. Рекомендуешь UserAdmin?

2021-03-25 14:41 UTC, makushenk commented on my_auth/admin.py
> +class CustomUserAdmin(DjangoUserAdmin):
я бы убрал Custom, да

2021-03-26 07:45 UTC, makushenk commented
@alushpanov конфликты)

2021-03-26 08:25 UTC, makushenk approved these changes

2021-03-26 08:25 UTC, merged